### ISSUE TITLE
Ajuste formulário

### ISSUE THREAD

**Issue by feliperodsdev** [Thasyo/one-piece#1]
Fiz algumas modificações para ajustar o formulário que fica no lado direito da página. Eu retirei a imagem pois não achei que encaixa bem, mas basta colocar ela e ajustar a largura e ficaria legal com uma borda arredondada.
![Capture](https://user-images.githubusercontent.com/105575030/184953609-ce0e2bef-3175-4417-b9fd-ddd284a51c7d.PNG)
Se quiser, envio o CSS e o HTML que editei.

**Comment by Thasyo** [comment]
Olá, eu ainda não iniciei essa parte do projeto, ainda vou estilizar ela, mas muito obrigado pela sugestão e pelo feedback!!  :)

**Comment by Thasyo** [comment]
Olá, eu ainda não iniciei essa parte do projeto, vou estilizar ela ainda, mas muito obrigado pela sugestão e pelo feedback!!  :)

**Comment by Thasyo** [comment]
Olá, ainda não iniciei a estilização dessa parte do projeto, mas muito obrigado pela sugestão e pelo feedback!  :)
